# Generated by Django 5.1.2 on 2024-12-01 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=255)),
                ('client_reference', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('company_address', models.CharField(max_length=255)),
                ('company_reference', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Responsible',
            fields=[
                ('responsible_id', models.AutoField(primary_key=True, serialize=False)),
                ('responsible_user_id', models.IntegerField()),
                ('responsible_name', models.CharField(max_length=255)),
                ('responsible_username', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('rol', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255)),
                ('project_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('project_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
                ('project_responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.responsible')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('offer_id', models.AutoField(primary_key=True, serialize=False)),
                ('offer_title', models.CharField(max_length=255)),
                ('offer_reference', models.CharField(max_length=255)),
                ('offer_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.client')),
                ('offer_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.company')),
                ('offer_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
                ('offer_responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.responsible')),
            ],
        ),
    ]
