# Generated by Django 5.1.2 on 2024-10-30 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_authuser_options_alter_authuser_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=255)),
                ('client_reference', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('company_address', models.CharField(max_length=255)),
                ('company_reference', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Responsible',
            fields=[
                ('responsible_id', models.AutoField(primary_key=True, serialize=False)),
                ('responsible_user_id', models.IntegerField()),
                ('responsible_name', models.CharField(max_length=255)),
                ('responsible_username', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255)),
                ('project_client', models.CharField(max_length=255)),
                ('project_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('project_responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.responsible')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('offer_id', models.AutoField(primary_key=True, serialize=False)),
                ('offer_title', models.CharField(max_length=255)),
                ('offer_reference', models.CharField(max_length=255)),
                ('offer_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer_client_company', models.CharField(max_length=255)),
                ('offer_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
                ('offer_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
                ('offer_responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.responsible')),
            ],
        ),
    ]
